# Generated by Django 5.2.7 on 2025-10-22 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0007_alter_callsession_customer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='hume_config_id',
            field=models.CharField(blank=True, help_text='HumeAI EVI Config ID (auto-populated when agent is created)', max_length=200, null=True),
        ),
    ]
