# Generated by Django 5.2.7 on 2025-10-26 09:49

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agents', '0008_agent_hume_config_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoCallCampaign',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('campaign_type', models.CharField(choices=[('sales', 'Sales'), ('followup', 'Follow-up'), ('survey', 'Survey'), ('reminder', 'Reminder'), ('test', 'Test')], default='sales', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('target_customers', models.PositiveIntegerField(default=10)),
                ('calls_per_hour', models.PositiveIntegerField(default=5)),
                ('working_hours_start', models.CharField(default='09:00', max_length=5)),
                ('working_hours_end', models.CharField(default='17:00', max_length=5)),
                ('campaign_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('ai_agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auto_campaigns', to='agents.aiagent')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoCampaignContact',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('calling', 'Calling'), ('completed', 'Completed'), ('failed', 'Failed'), ('skipped', 'Skipped')], default='pending', max_length=20)),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Medium'), (3, 'High'), (4, 'Urgent')], default=2)),
                ('scheduled_datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('call_started_at', models.DateTimeField(blank=True, null=True)),
                ('call_completed_at', models.DateTimeField(blank=True, null=True)),
                ('call_outcome', models.CharField(blank=True, max_length=50)),
                ('failure_reason', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='agents.autocallcampaign')),
                ('customer_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_contacts', to='agents.customerprofile')),
            ],
            options={
                'ordering': ['-priority', 'scheduled_datetime'],
                'unique_together': {('campaign', 'customer_profile')},
            },
        ),
    ]
