# Generated by Django 5.2.7 on 2025-10-29 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumeAiTwilio', '0002_learned_knowledge_models'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='learnedknowledge',
            new_name='idx_question',
            old_name='HumeAiTwil_questio_idx',
        ),
        migrations.RenameIndex(
            model_name='learnedknowledge',
            new_name='idx_source_created',
            old_name='HumeAiTwil_source_idx',
        ),
        migrations.AddField(
            model_name='twiliocall',
            name='hume_config_id',
            field=models.CharField(blank=True, help_text='HumeAI Configuration ID used for this call', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='twiliocall',
            name='provider',
            field=models.CharField(choices=[('twilio', 'Twilio'), ('vonage', 'Vonage')], default='twilio', help_text='Voice service provider', max_length=20),
        ),
        migrations.AlterField(
            model_name='twiliocall',
            name='call_sid',
            field=models.CharField(help_text='Call ID from provider (Twilio SID or Vonage UUID)', max_length=255, unique=True),
        ),
        migrations.AlterModelTable(
            name='callconversation',
            table='call_conversations',
        ),
        migrations.AlterModelTable(
            name='learnedknowledge',
            table='learned_knowledge',
        ),
        migrations.AlterModelTable(
            name='trainingdocument',
            table='training_documents',
        ),
    ]
