# Generated by Django 5.2.7 on 2025-11-03 08:30

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumeAiTwilio', '0003_rename_humeaitwil_questio_idx_idx_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, help_text='Primary phone number', max_length=20, unique=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('preferred_language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('total_calls', models.IntegerField(default=0)),
                ('last_call_date', models.DateTimeField(blank=True, null=True)),
                ('learned_preferences', models.JSONField(blank=True, help_text='Any preferences mentioned by customer', null=True)),
                ('previous_topics', models.JSONField(blank=True, help_text='Topics discussed in previous calls', null=True)),
                ('custom_fields', models.JSONField(blank=True, help_text='Additional custom data learned', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Customer Profile',
                'verbose_name_plural': 'Customer Profiles',
                'db_table': 'hume_customer_profiles',
                'ordering': ['-last_call_date'],
                'indexes': [models.Index(fields=['phone_number'], name='hume_custom_phone_n_46f26a_idx'), models.Index(fields=['full_name'], name='hume_custom_full_na_a84d89_idx'), models.Index(fields=['-last_call_date'], name='hume_custom_last_ca_2401a7_idx')],
            },
        ),
        migrations.AddField(
            model_name='twiliocall',
            name='customer_profile',
            field=models.ForeignKey(blank=True, help_text='Linked customer profile', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calls', to='HumeAiTwilio.customerprofile'),
        ),
    ]
