# Generated by Django 5.2.7 on 2025-11-03 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumeAiTwilio', '0004_customerprofile_twiliocall_customer_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='humeagent',
            name='business_info',
            field=models.JSONField(blank=True, default=dict, help_text='Business information: company_name, website, industry, greeting, etc.'),
        ),
        migrations.AddField(
            model_name='humeagent',
            name='knowledge_files',
            field=models.JSONField(blank=True, default=dict, help_text='Knowledge base: product_catalog, pricing, features, FAQs, etc.'),
        ),
        migrations.AddField(
            model_name='humeagent',
            name='sales_script_text',
            field=models.TextField(blank=True, help_text='Sales script text for the agent to follow during calls', null=True),
        ),
    ]
