# Generated by Django 5.2.7 on 2025-11-05 01:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HumeAiTwilio', '0005_humeagent_business_info_humeagent_knowledge_files_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CallObjection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('objection_type', models.CharField(choices=[('price', 'Price/Budget'), ('timing', 'Timing/Not Ready'), ('competition', 'Competitor Comparison'), ('authority', 'Need Approval'), ('need', 'No Perceived Need'), ('trust', 'Trust/Credibility'), ('feature', 'Missing Feature'), ('support', 'Support Concerns'), ('contract', 'Contract Terms'), ('other', 'Other')], max_length=20)),
                ('objection_text', models.TextField(help_text="Customer's objection statement")),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('clarifies_step', models.CharField(help_text='Which CLARIFIES step was used to address this', max_length=50)),
                ('agent_response', models.TextField(help_text='How agent responded')),
                ('resolution_status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('escalated', 'Escalated'), ('unresolved', 'Unresolved')], default='pending', max_length=20)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('confidence_score', models.FloatField(default=0.0, help_text='AI confidence in objection detection (0-1)')),
                ('sentiment_before', models.CharField(blank=True, max_length=20)),
                ('sentiment_after', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objections', to='HumeAiTwilio.twiliocall')),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.CreateModel(
            name='CLARIFIESStep',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('step_type', models.CharField(choices=[('C', 'Concern - Identify customer concern'), ('L', 'Listen - Active listening'), ('A', 'Acknowledge - Acknowledge feelings'), ('R', 'Respond - Respond with empathy'), ('I', 'Inform - Provide information'), ('F', 'Find - Find solutions'), ('I2', 'Involve - Involve customer in solution'), ('E', 'Ensure - Ensure understanding'), ('S', 'Seal - Close the deal')], max_length=2)),
                ('step_number', models.IntegerField(help_text='Sequential step number in conversation')),
                ('customer_message', models.TextField(blank=True)),
                ('agent_message', models.TextField(blank=True)),
                ('reasoning', models.TextField(help_text='Why this step was chosen')),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('decision_factors', models.JSONField(default=dict, help_text='Factors that led to this step: sentiment, keywords, context')),
                ('alternative_paths', models.JSONField(default=list, help_text='Other possible steps that were considered')),
                ('effectiveness_score', models.FloatField(default=0.0, help_text='How effective was this step (0-1)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clarifies_steps', to='HumeAiTwilio.twiliocall')),
                ('objection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clarifies_steps', to='HumeAiTwilio.callobjection')),
            ],
            options={
                'ordering': ['call', 'step_number'],
            },
        ),
        migrations.CreateModel(
            name='ConversationAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('outcome', models.CharField(choices=[('won', 'Won - Sale Closed'), ('lost', 'Lost - Not Interested'), ('follow_up', 'Follow-up Scheduled'), ('escalated', 'Escalated to Human'), ('incomplete', 'Call Incomplete')], default='incomplete', max_length=20)),
                ('win_probability', models.FloatField(default=0.0, help_text='Predicted win rate (0-1)')),
                ('total_objections', models.IntegerField(default=0)),
                ('objections_resolved', models.IntegerField(default=0)),
                ('objections_escalated', models.IntegerField(default=0)),
                ('clarifies_steps_used', models.JSONField(default=list, help_text='List of CLARIFIES steps used in order')),
                ('total_steps', models.IntegerField(default=0)),
                ('avg_sentiment', models.FloatField(default=0.0)),
                ('sentiment_trend', models.CharField(choices=[('improving', 'Improving'), ('declining', 'Declining'), ('stable', 'Stable')], default='stable', max_length=20)),
                ('customer_talk_time_seconds', models.IntegerField(default=0)),
                ('agent_talk_time_seconds', models.IntegerField(default=0)),
                ('total_turns', models.IntegerField(default=0, help_text='Number of back-and-forth exchanges')),
                ('dominant_customer_emotion', models.CharField(blank=True, max_length=50)),
                ('emotion_breakdown', models.JSONField(default=dict, help_text='Distribution of emotions throughout call')),
                ('key_decision_moments', models.JSONField(default=list, help_text='Critical moments that influenced outcome')),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('call', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clarifies_analytics', to='HumeAiTwilio.twiliocall')),
            ],
            options={
                'verbose_name_plural': 'Conversation Analytics',
            },
        ),
        migrations.CreateModel(
            name='RiskFlag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flagged_content', models.TextField(help_text='The content that was flagged')),
                ('flag_reason', models.TextField(help_text='Why this content was flagged')),
                ('matched_pattern', models.CharField(help_text='Regex pattern that matched', max_length=255)),
                ('risk_level', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('critical', 'Critical Risk')], max_length=20)),
                ('risk_category', models.CharField(help_text='e.g., profanity, legal_claim, medical_advice', max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('auto_blocked', 'Auto-Blocked')], default='pending', max_length=20)),
                ('was_blocked', models.BooleanField(default=True, help_text='Was message blocked from customer?')),
                ('replacement_sent', models.TextField(blank=True, help_text='Alternative message sent if blocked')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True)),
                ('detected_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('call', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_flags', to='HumeAiTwilio.twiliocall')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-detected_at'],
            },
        ),
        migrations.AddIndex(
            model_name='callobjection',
            index=models.Index(fields=['call', 'objection_type'], name='HumeAiTwili_call_id_38e324_idx'),
        ),
        migrations.AddIndex(
            model_name='callobjection',
            index=models.Index(fields=['resolution_status'], name='HumeAiTwili_resolut_73957c_idx'),
        ),
        migrations.AddIndex(
            model_name='clarifiesstep',
            index=models.Index(fields=['call', 'step_number'], name='HumeAiTwili_call_id_12ccb9_idx'),
        ),
        migrations.AddIndex(
            model_name='clarifiesstep',
            index=models.Index(fields=['step_type'], name='HumeAiTwili_step_ty_4579fb_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationanalytics',
            index=models.Index(fields=['outcome'], name='HumeAiTwili_outcome_c891ba_idx'),
        ),
        migrations.AddIndex(
            model_name='conversationanalytics',
            index=models.Index(fields=['analyzed_at'], name='HumeAiTwili_analyze_1a76d9_idx'),
        ),
        migrations.AddIndex(
            model_name='riskflag',
            index=models.Index(fields=['call', 'detected_at'], name='HumeAiTwili_call_id_e8ea7f_idx'),
        ),
        migrations.AddIndex(
            model_name='riskflag',
            index=models.Index(fields=['status', 'risk_level'], name='HumeAiTwili_status_1e400b_idx'),
        ),
        migrations.AddIndex(
            model_name='riskflag',
            index=models.Index(fields=['risk_category'], name='HumeAiTwili_risk_ca_b42421_idx'),
        ),
    ]
